### ISSUE TITLE
add skale tipping token list

### ISSUE THREAD

**Issue by iSpeakNerd** [abridged/collabland-dev#151]
https://docs.google.com/spreadsheets/d/1fD4cMSVyry5Yd-WSIfgTY9DWsCJ8YCdMg2WsF02POz4/edit#gid=1794733328

**Comment by gitaalekhyapaul** [comment]
@iSpeakNerd updated the list with the stablecoins data
We have 27 tokens mapped as of now on the Calypso SKALE mainnet

**Comment by iSpeakNerd** [comment]
Collab.Land docs https://docs.collab.land/help-docs/marketplace/apps/give#supported-tokens
